### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by RashikaAbca51** [sodafoundation/contrib-lab01#108]
Unable to login into existing #account.
![Screenshot (17)](https://user-images.githubusercontent.com/122352946/212856062-6d70706b-655d-4141-ab69-3024eea62164.png)
[issue#1.docx](https://github.com/sodafoundation/contrib-lab01/files/10433242/issue.1.docx)

**Comment by MASTERRAJESH** [comment]
turn on the network
