### ISSUE TITLE
Bug in registration Form 

### ISSUE THREAD

**Issue by Nrj007** [sodafoundation/contrib-lab01#113]
A bug was spotted in update   button in registration module. Update  button is not saving the updated details in  the registration module.
 
Attached the screenshot below!!
![image](https://user-images.githubusercontent.com/95224756/212859301-e5abd04d-3c87-462a-b89b-4af0d5148e3d.png)

Please go through and make necessary changes accordingly.

**Comment by Nish2003** [comment]
^_^

**Comment by arnjodpk7** [comment]
scn...

**Comment by Misfarz** [comment]
wow
