### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by arnjodpk7** [sodafoundation/contrib-lab01#116]
![Screenshot (18)](https://user-images.githubusercontent.com/122352748/212856867-80eecf71-66e2-4ab7-88f4-e4fe6fbc9589.png)

**Comment by Nrj007** [comment]
where is the issue?

**Comment by arnjodpk7** [comment]
ninthe kindi poda

**Comment by ImposterHigh** [comment]
Whats the issue

**Comment by ImposterHigh** [comment]
Close it

**Comment by ImposterHigh** [comment]
> where is the issue?

You are the issue
