### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by MonishGr** [sodafoundation/contrib-lab01#125]
**Issue/Feature Description:**
  Im not able to connect to the server
**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

[Github.docx](https://github.com/sodafoundation/contrib-lab01/files/10433236/Github.docx)

**Comment by RashikaAbca51** [comment]
Proof needed. Attach SS

**Comment by prakruthirinku** [comment]
wht a big issue omg

**Comment by revelation3** [comment]
give 10rs i will solve
