### ISSUE TITLE
Error in opening file

### ISSUE THREAD

**Issue by ts2865** [sodafoundation/contrib-lab01#128]
**it's showing error while opening this file :**

due to error 404 I am not able to open this file and its showing check the link

how to solve this error as its working for others

: (Please give the necessary information, log link or any useful information for this issue)**

![image](https://user-images.githubusercontent.com/122352450/212857445-eb5ca0a9-4f30-49af-b3b2-c99e9af96c90.png)

[https://forms.gle/eugedSizvGCdy86H7](url)

**Comment by mr0weird0guy** [comment]
is that 404 not found issue related to your social life

**Comment by ts2865** [comment]
yes after meeting you my life has become error 404
