### ISSUE TITLE
new issue cause last one was closed

### ISSUE THREAD

**Issue by mr0weird0guy** [sodafoundation/contrib-lab01#84]
![image](https://user-images.githubusercontent.com/85097731/212857329-8d789b8d-aacb-4a1b-9855-10ced17d7160.png)

Idk why but we are told to create new issue even though there is almost no content in the project regarding which we can create new issue

**Comment by mr0weird0guy** [comment]
![image](https://user-images.githubusercontent.com/85097731/212856928-d0964504-b516-4765-aab0-6950fccea676.png)
gmail.com not opening

**Comment by prakruthirinku** [comment]
thts the big issue

**Comment by ts2865** [comment]
because you are greatest issue I have ever met
