### ISSUE TITLE
gmail login ISSUES

### ISSUE THREAD

**Issue by MASTERRAJESH** [sodafoundation/contrib-lab01#98]
NOT UPDATED
![jd master](https://user-images.githubusercontent.com/122866905/212856047-09d4d1b4-45a4-4fa5-8150-749fe477b444.png)
and this is the ui page

![Annotation 2023-01-17 144445](https://user-images.githubusercontent.com/122866905/212857462-2e52c7d2-1729-4bf5-ad2d-91de9c23b91f.png)

**Comment by prakruthirinku** [comment]
wht is jd

**Comment by AdolfMarshal** [comment]
(❁´◡`❁)

**Comment by MASTERRAJESH** [comment]
jd is one of the powerfull program
